name: test

on: 
  push:
    branches:
      - "dev"
      - "master"
      - "main"

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
      - name: Say hello world
        shell: bash
        run: echo Welcome to the Github Actions workshop !

  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit-tests
        shell: bash
        run: make unit-tests
      
      - name: Get coverage
        shell: bash
        run: make coverage